name: Run Selenium Tests with Behave

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: |
          pip install selenium behave webdriver-manager
          
      - name: Run tests
        run: |
          mkdir -p reports
          behave --format json --out reports/report.json
          
      - uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
